---
- name: install dependencies
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - dnf-plugins-core
      - gnupg2

- name: import epel gpg keys
  ansible.builtin.rpm_key:
    key: "{{ epel_rpm_key }}"
    state: present

- name: install epel-release
  ansible.builtin.dnf:
    name:
      - "{{ epel_url }}"
    state: present

- name: ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  when: >-
    (ansible_facts["distribution"] == "CentOS" and ansible_facts["distribution_major_version"]|int > 8) or
    (ansible_facts["distribution"] == "Rocky" and ansible_facts["distribution_major_version"]|int > 8)
