---

- name: install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: import epel gpg keys
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: install epel-release
  ansible.builtin.dnf:
    name:
      - "{{ epel_url }}"
      - "{{ epel_next_url }}"
    state: present

- name: enable crb repository
  command:
    cmd: dnf config-manager --enable crb
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int > 8) or
        (ansible_distribution == "Rocky" and ansible_distribution_major_version|int > 8)

- name: enable codeready-builder-for-rhel-9
  community.general.rhsm_repository:
    name: "codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 9
