# - name: install RPM-GPG-KEY-EPEL-8
#   rpm_key:
#     state: present
#     key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

- name: install dnf-plugins-core
  action: "{{ ansible_pkg_mgr }} name=dnf-plugins-core state=present"

- name: import epel gpg keys
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: install epel-release
  dnf:
    name:
      - "{{ epel_url }}"
      - "{{ epel_next_url }}"
    state: present

- name: enable crb
  command:
    cmd: dnf config-manager --set-enabled crb
  changed_when: false
