- name: install RPM-GPG-KEY-EPEL-8
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

- name: install dnf-plugins-core
  action: "{{ ansible_pkg_mgr }} name=dnf-plugins-core state=present"

- name: install epel-release
  dnf:
    name:
      - epel-release
      - epel-next-release
    state: present

- name: enable power tools repository
  command:
    cmd: dnf config-manager --set-enabled powertools
  changed_when: false
