---
dependency:
  command: >
    ansible-galaxy install -fr
    ${MOLECULE_SCENARIO_DIRECTORY}/../../requirements.yaml
  name: shell
driver:
  name: docker
platforms:
  - image: ghcr.io/escapace/ansible-test-containers
    name: instance
    pre_build_image: true
prerun: false
provisioner:
  name: ansible
  playbooks:
    converge: '${CONVERGE_PLAYBOOK:-converge.yaml}'
